#!/bin/bash

echo "🔍 Checking deployment transaction on BSCScan..."
echo ""
echo "1. Go to: https://testnet.bscscan.com/tx/0x3d481a87990a750c6b036eb5d8fec0764cb46c51e96281e8b0b31db1cf36989f"
echo ""
echo "2. Look for 'Input Data' section"
echo ""
echo "3. Click 'Decode Input Data' button"
echo ""
echo "4. You'll see the exact constructor parameters used"
echo ""
echo "5. Copy those values for BSCScan verification"
echo ""
echo "📋 Verification Settings:"
echo "   - Compiler: v0.8.20+commit.a1b79de6"
echo "   - Optimization: Yes"
echo "   - Runs: 200"
echo "   - License: MIT"
echo ""
echo "💡 Tip: BSCScan can auto-detect constructor args from deployment transaction"
